"""Small idempotent schema and data compatibility updates for existing BITCRM databases."""
from sqlalchemy import inspect, text

from extensions import db


COLUMN_UPDATES = {
    'sales_leads': {
        'follow_up': 'TEXT',
        'is_deleted': 'BOOLEAN NOT NULL DEFAULT FALSE',
        'deleted_at': 'TIMESTAMP NULL',
        'deleted_by_id': 'INTEGER NULL',
    },
    'pipeline': {
        'is_deleted': 'BOOLEAN NOT NULL DEFAULT FALSE',
        'deleted_at': 'TIMESTAMP NULL',
        'deleted_by_id': 'INTEGER NULL',
    },
    'tasks': {
        'sales_lead_id': 'INTEGER NULL',
        'sales_activity_id': 'INTEGER NULL',
        'completion_notes': 'TEXT NULL',
        'completed_at': 'TIMESTAMP NULL',
        'completed_by_id': 'INTEGER NULL',
        'is_deleted': 'BOOLEAN NOT NULL DEFAULT FALSE',
        'deleted_at': 'TIMESTAMP NULL',
        'deleted_by_id': 'INTEGER NULL',
    },
    'sales_activities': {
        'remote_engagement_subtype': 'VARCHAR(40) NULL',
        'completion_notes': 'TEXT NULL',
        'cancelled_at': 'TIMESTAMP NULL',
        'cancelled_by_id': 'INTEGER NULL',
        'cancellation_reason': 'TEXT NULL',
    },
    'activity_logs': {
        'old_values': 'TEXT NULL',
        'new_values': 'TEXT NULL',
        'extra_data': 'TEXT NULL',
    },
}


LEGACY_SALES_ACTIVITY_TYPE_NAMES = {
    'Online': 'Remote Engagement',
    'Field Visit': 'Customer Visit',
    'On-site Visit': 'Customer Visit',
    'Out of Building Visit': 'Customer Visit',
}

LEGACY_SALES_ACTIVITY_SOURCE_NAMES = {
    'Marketing Event': 'Event',
}

# These fields contain user-visible descriptions generated by the application.
TERMINOLOGY_TEXT_COLUMNS = (
    ('sales_leads', 'follow_up'),
    ('pipeline', 'follow_up'),
    ('tasks', 'content'),
    ('activity_logs', 'description'),
    ('activity_logs', 'old_values'),
    ('activity_logs', 'new_values'),
    ('activity_logs', 'extra_data'),
)


def _rename_remote_engagement_subtype_column():
    """Rename the legacy subtype column while preserving existing data."""
    inspector = inspect(db.engine)
    if 'sales_activities' not in inspector.get_table_names():
        return

    columns = {column['name'] for column in inspector.get_columns('sales_activities')}
    legacy_column = 'online_subtype'
    current_column = 'remote_engagement_subtype'
    if legacy_column in columns and current_column not in columns:
        try:
            db.session.execute(text(
                f'ALTER TABLE "sales_activities" RENAME COLUMN "{legacy_column}" TO "{current_column}"'
            ))
            db.session.commit()
        except Exception:
            # Another application worker may have completed this idempotent rename.
            db.session.rollback()
            refreshed_columns = {
                column['name'] for column in inspect(db.engine).get_columns('sales_activities')
            }
            if current_column not in refreshed_columns:
                raise



def _ensure_sales_activity_type_capacity():
    """Allow canonical activity names longer than the legacy VARCHAR(20)."""
    inspector = inspect(db.engine)
    if 'sales_activities' not in inspector.get_table_names():
        return
    columns = {column['name']: column for column in inspector.get_columns('sales_activities')}
    activity_type = columns.get('activity_type')
    current_length = getattr(activity_type.get('type'), 'length', None) if activity_type else None
    if not current_length or current_length >= 40:
        return

    dialect = db.engine.dialect.name
    if dialect == 'sqlite':
        # SQLite does not enforce VARCHAR lengths, so existing databases can store
        # the longer canonical names without rebuilding the table.
        return
    ddl = (
        'ALTER TABLE "sales_activities" ALTER COLUMN "activity_type" TYPE VARCHAR(40)'
        if dialect == 'postgresql'
        else 'ALTER TABLE `sales_activities` MODIFY COLUMN `activity_type` VARCHAR(40) NOT NULL'
    )
    try:
        db.session.execute(text(ddl))
        db.session.commit()
    except Exception:
        db.session.rollback()
        refreshed = {column['name']: column for column in inspect(db.engine).get_columns('sales_activities')}
        refreshed_length = getattr(refreshed['activity_type']['type'], 'length', None)
        if refreshed_length and refreshed_length < 40:
            raise

def ensure_sales_activity_columns():
    """Add or rename columns before ORM queries touch an existing database."""
    _rename_remote_engagement_subtype_column()
    _ensure_sales_activity_type_capacity()
    inspector = inspect(db.engine)
    tables = set(inspector.get_table_names())
    for table_name, columns in COLUMN_UPDATES.items():
        if table_name not in tables:
            continue
        existing = {column['name'] for column in inspector.get_columns(table_name)}
        for column_name, ddl_type in columns.items():
            if column_name in existing:
                continue
            db.session.execute(text(
                f'ALTER TABLE "{table_name}" ADD COLUMN "{column_name}" {ddl_type}'
            ))
            db.session.commit()
            existing.add(column_name)


def ensure_sales_activity_terminology():
    """Migrate stored activity names and generated descriptions to current terms."""
    inspector = inspect(db.engine)
    tables = set(inspector.get_table_names())
    if 'sales_activities' not in tables:
        return

    terminology_updates = (
        ('activity_type', LEGACY_SALES_ACTIVITY_TYPE_NAMES),
        ('source_type', LEGACY_SALES_ACTIVITY_SOURCE_NAMES),
    )
    text_replacements = []
    for column_name, replacements in terminology_updates:
        for legacy_name, current_name in replacements.items():
            db.session.execute(
                text(
                    'UPDATE "sales_activities" '
                    f'SET "{column_name}" = :current_name '
                    f'WHERE "{column_name}" = :legacy_name'
                ),
                {'legacy_name': legacy_name, 'current_name': current_name},
            )
            text_replacements.append((legacy_name, current_name))

    for legacy_name, current_name in text_replacements:
        for table_name, column_name in TERMINOLOGY_TEXT_COLUMNS:
            if table_name not in tables:
                continue
            columns = {column['name'] for column in inspector.get_columns(table_name)}
            if column_name not in columns:
                continue
            db.session.execute(
                text(
                    f'UPDATE "{table_name}" '
                    f'SET "{column_name}" = REPLACE("{column_name}", :legacy_name, :current_name) '
                    f'WHERE "{column_name}" LIKE :pattern'
                ),
                {
                    'legacy_name': legacy_name,
                    'current_name': current_name,
                    'pattern': f'%{legacy_name}%',
                },
            )

    db.session.commit()


def ensure_sales_activity_statuses():
    """Migrate the legacy open status to the new scheduled business state."""
    inspector = inspect(db.engine)
    if 'sales_activities' not in inspector.get_table_names():
        return
    db.session.execute(text(
        'UPDATE "sales_activities" SET "status" = :scheduled '
        'WHERE "status" = :legacy_status'
    ), {'scheduled': 'Scheduled', 'legacy_status': 'Pending Follow-up'})
    db.session.commit()
